### ISSUE TITLE
Improve the way in which logs are kept and shown to the user.

### ISSUE THREAD

**Issue by gtato** [ConPaaS-team/conpaas#101]
Every service should be able to expose a custom list of log files which are relevant for the specific service. Ideally, this list should be dynamic, so it can be changed during the lifetime of the service to accommodate the specific needs at that point in time (for example, in the Generic Service, different applications deployed in the cloud may want to expose a different set of log files).

All these log files, along with the application manager log, service manager logs and agent logs should be accessible in a centralized manner.

**Comment by tcrivat** [comment]
The application manager log is exposed in the web frontend since commit 16f7e825faeb58e2018fd4b50df5032bfcfb587c.

Separate logs for service managers (and links for retrieving them from the web frontend) are implemented in commit fe45dad9f2105a386d3db5b29b3c813d9d2e2e49. They are now accessible also using the command line client (cps-tools) since commit 713039aedc71cd8a1e8e76ffa21664da4ed6b7b4.

Agent logs are retrievable in both the web frontend and command line client for all the services since the commit c006659b5a9dbc5bf7bbde677ec964dd65270bf6.

However, the list of logs that a service can export is not dynamic and, at the moment, for the agents, only the ConPaaS Agent's log is accessible. Since we have another issue that request to make this customizable for every service (#92), I will close the current issue.
