### ISSUE TITLE
xtreemfs request time out error 

### ISSUE THREAD

**Issue by gtato** [ConPaaS-team/conpaas#72]
Hi, 
I created a PHP service and a xtreemfs one using rc5 on OpenNebula.
When tried to mount the xtreemfs module on the PHP agent.
I get the following error
```
[ E |  9/26 14:26:51.349 | 0x1c81430      ] Got no response from server 10.100.43.2:32638, retrying (infinite attempts left)
```
I went on the xtreemfs agent and tried to list the volumes and I got this:
```
Listing all volumes of the MRC: localhost
[ E |  9/26 16:13:13.776 | 0x26d3cc0      ] The client encountered a communication error sending a request to the server: localhost:32636. Error: Request timed out (call id = 1, interface id = 20001, proc id = 36, server = localhost:32636).
Failed to list the volumes, error:
	Request timed out (call id = 1, interface id = 20001, proc id = 36, server = localhost:32636).
```
@noma, @tschuett any idea what is going wrong?

**Comment by tcrivat** [comment]
This was now fixed in XtreemFS 1.5.1 by adding the message "(Possible reason: The server is using SSL, and the client is not.)", so after the timeout the following message is now printed:

root@conpaas:~# mount.xtreemfs 192.168.122.25/data /var/data
[ E |  3/24 12:27:25.514 | 0x236fff0      ] Got no response from server 192.168.122.25:32638, retrying (infinite attempts left) (Possible reason: The server is using SSL, and the client is not.)

This can now be closed.
